version: '3'
services:
  db:
    image: postgres
  api:
    build: .
    command: bundle exec bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
     - .:/forum
    ports:
     - "3000:3000"
    depends_on:
     - db